Repository samtuap/dongsanginong-server, pull requests merged in 2024-09, with the labels that each got.

#4 chore: SwaggerConfig 세팅
  backend/live/src/main/java/org/samtuap/inong/config/SwaggerConfig.java
  backend/member/src/main/java/org/samtuap/inong/config/SwaggerConfig.java
  backend/order/src/main/java/org/samtuap/inong/config/SwaggerConfig.java
  backend/product/src/main/java/org/samtuap/inong/config/SwaggerConfig.java
Labels: 🧹chore

#6 chore: build.gradle에 카프카 의존성 추가, application-local.yml에 카프카 설정 추가
  backend/live/build.gradle
  backend/live/src/main/resources/application-local.yml
  backend/member/build.gradle
  backend/member/src/main/resources/application-local.yml
  backend/order/build.gradle
  backend/order/src/main/resources/application-local.yml
  backend/product/build.gradle
  backend/product/src/main/resources/application-local.yml
Labels: 🧹chore

#16 feat: kakao 로그인 및 회원가입 구현, gateway-member JWT 세팅
  backend/apigateway/build.gradle
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
  backend/apigateway/src/main/java/org/samtuap/inong/securities/configs/RedisConfig.java
  backend/apigateway/src/main/resources/application-local.yml
  backend/member/build.gradle
  backend/member/src/main/java/org/samtuap/inong/domain/member/api/MemberController.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/MemberInfoServiceResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/SignInRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/SignInResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/SignUpRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/SignUpResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/entity/Member.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/entity/SocialType.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/jwt/config/RedisConfig.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/jwt/domain/JwtToken.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/jwt/domain/JwtValidator.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/jwt/domain/SecretKeyFactory.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/jwt/service/JwtService.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/oauth/kakao/config/KakaoOAuthConfig.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/oauth/kakao/dto/KakaoAccountServiceResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/oauth/kakao/dto/KakaoGetMemberInfoServiceResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/oauth/kakao/dto/KakaoUserInfoResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/oauth/kakao/service/KakaoService.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/oauth/service/OAuthService.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/repository/MemberRepository.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/securities/JwtProvider.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/service/MemberService.java
  backend/member/src/main/resources/application-local.yml
Labels: ✨feature

#23 chore: BaseCustomException과 에러 응답 객체 세팅
  backend/live/src/main/java/org/samtuap/inong/common/exception/BaseCustomException.java
  backend/live/src/main/java/org/samtuap/inong/common/exceptionType/ExceptionType.java
  backend/live/src/main/java/org/samtuap/inong/common/handler/GlobalExceptionHandler.java
  backend/live/src/main/java/org/samtuap/inong/common/response/CustomErrorResponse.java
  backend/member/src/main/java/org/samtuap/inong/common/exception/BaseCustomException.java
  backend/member/src/main/java/org/samtuap/inong/common/exceptionType/ExceptionType.java
  backend/member/src/main/java/org/samtuap/inong/common/handler/GlobalExceptionHandler.java
  backend/member/src/main/java/org/samtuap/inong/common/response/CustomErrorResponse.java
  backend/order/src/main/java/org/samtuap/inong/common/exception/BaseCustomException.java
  backend/order/src/main/java/org/samtuap/inong/common/exceptionType/ExceptionType.java
  backend/order/src/main/java/org/samtuap/inong/common/handler/GlobalExceptionHandler.java
  backend/order/src/main/java/org/samtuap/inong/common/response/CustomErrorResponse.java
  backend/product/src/main/java/org/samtuap/inong/common/exception/BaseCustomException.java
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/ExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/ProductExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/common/handler/GlobalExceptionHandler.java
  backend/product/src/main/java/org/samtuap/inong/common/response/CustomErrorResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/api/ProductController.java
Labels: 🧹chore

#21 feat: 공지 생성 및 수정
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/api/FarmNoticeController.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/dto/NoticeCreateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/dto/NoticeImageDto.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/dto/NoticeUpdateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/entity/FarmNotice.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/entity/FarmNoticeImage.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/repository/FarmNoticeImageRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/service/FarmNoticeService.java
Labels: ✨feature

#26 feature:판매자 회원가입 및 이메일 인증
  backend/product/build.gradle
  backend/product/src/main/java/org/samtuap/inong/config/EmailConfig.java
  backend/product/src/main/java/org/samtuap/inong/config/RedisConfig.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/.gitkeep
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/EmailVerificationController.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/SellerController.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/dto/CommonResDto.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/dto/SellerSignUpRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/entity/Seller.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/repository/SellerRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/.gitkeep
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/EmailTool.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/EmailVerificationService.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/RedisTool.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/SellerService.java
  backend/product/src/main/resources/application-local.yml
Labels: ✨feature

#28 feat: 판매자 공지 삭제 && 에러 처리 변경
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/ProductExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/api/FarmNoticeController.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/repository/NoticeCommentRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/service/FarmNoticeService.java
Labels: ✨feature

#34 chore: Member 모듈 BaseCustomException 적용
  backend/member/src/main/java/org/samtuap/inong/common/exceptionType/MemberExceptionType.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/oauth/google/service/GoogleService.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/oauth/kakao/service/KakaoService.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/service/MemberService.java
Labels: 🧹chore

#38 chore: JWT > 식별을 위한 Role 추가
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/entity/MemberRole.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/jwt/securities/JwtProvider.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/jwt/service/JwtService.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/service/MemberService.java
  backend/member/src/main/resources/application-local.yml
Labels: 🧹chore

#32 feat: 농장 조회 API 생성
  backend/member/src/main/java/org/samtuap/inong/domain/common/BaseEntity.java
  backend/product/src/main/java/org/samtuap/inong/common/client/MemberFeign.java
  backend/product/src/main/java/org/samtuap/inong/common/client/OrderFeign.java
  backend/product/src/main/java/org/samtuap/inong/config/FeignConfig.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/api/.gitkeep
  backend/product/src/main/java/org/samtuap/inong/domain/farm/api/FarmController.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/.gitkeep
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/FarmDetailGetResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/FarmListGetResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/entity/Farm.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/repository/FarmRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/.gitkeep
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/service/FarmNoticeService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/TopPackageResponse.java
Labels: ✨feature

#44 feature: 로그아웃 기능 추가
  backend/member/src/main/java/org/samtuap/inong/domain/member/api/MemberController.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/SignOutRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/jwt/config/RedisConfig.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/jwt/securities/JwtProvider.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/jwt/service/JwtService.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/service/MemberService.java
Labels: ✨feature

#45 feat: 메인 페이지 인기 패키지 조회, 농장 페이지 농장 검색 기능 구현
  backend/order/src/main/java/org/samtuap/inong/domain/order/api/.gitkeep
  backend/order/src/main/java/org/samtuap/inong/domain/order/api/OrderController.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/.gitkeep
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/TopPackageResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/repository/OrderRepository.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/.gitkeep
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
  backend/product/src/main/java/org/samtuap/inong/common/client/OrderFeign.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/api/FarmController.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/FarmSearchRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/repository/FarmRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/api/PackageProductController.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/.gitkeep
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/TopPackageGetResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/TopPackageResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/entity/PackageProduct.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/repository/PackageProductRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/.gitkeep
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
Labels: ✨feature

#47 feature: 판매자 로그인, 로그아웃 기능 추가
  backend/product/build.gradle
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/ProductExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/SellerController.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/dto/CommonResDto.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/dto/SellerSignInRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/dto/SellerSignInResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/dto/SellerSignOutRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/jwt/domain/JwtToken.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/jwt/domain/JwtValidator.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/jwt/domain/SecretKeyFactory.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/jwt/service/JwtService.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/securities/JwtProvider.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/SellerService.java
Labels: ✨feature

#52 feat: 회원 탈퇴 기능 추가
  backend/member/src/main/java/org/samtuap/inong/domain/member/api/MemberController.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/jwt/securities/JwtProvider.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/service/MemberService.java
  backend/member/src/main/resources/application-local.yml
Labels: ✨feature

#53 feature:판매자 회원 탈퇴
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/ProductExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/SellerController.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/SellerService.java
  backend/product/src/main/resources/application-local.yml
Labels: ✨feature

#56 feat: 일반 회원 정보 조회 기능 추가
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/api/MemberController.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/MemberInfoResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/repository/MemberRepository.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/service/MemberService.java
Labels: ✨feature

#58 feat: 일반 회원 정보 수정
  backend/member/src/main/java/org/samtuap/inong/domain/member/api/MemberController.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/MemberUpdateInfoRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/entity/Member.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/service/MemberService.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/repository/FarmRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/SellerController.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/dto/.gitkeep
  backend/product/src/main/java/org/samtuap/inong/domain/seller/dto/SellerInfoResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/repository/SellerRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/SellerService.java
Labels: ✨feature

#60 feat: 판매자 정보 조회
  backend/product/src/main/java/org/samtuap/inong/domain/farm/entity/FarmCategory.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/entity/FarmCategoryRelation.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/repository/FarmCategoryRelationRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/repository/FarmCategoryRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/dto/SellerInfoResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/SellerService.java
Labels: ✨feature

#63 feat: 상품 등록
  backend/product/build.gradle
  backend/product/src/main/java/org/samtuap/inong/config/AwsConfig.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/api/PackageProductController.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/api/S3Controller.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductCreateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductCreateResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/entity/PackageProduct.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/entity/PackageProductImage.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductImageService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/S3Service.java
  backend/product/src/main/resources/application-local.yml
Labels: ✨feature

#62 feat: 일반 회원 패키지 구독 정보 조회 (detail)
  backend/member/src/main/java/org/samtuap/inong/common/client/ProductFeign.java
  backend/member/src/main/java/org/samtuap/inong/common/exceptionType/SubscriptionExceptionType.java
  backend/member/src/main/java/org/samtuap/inong/config/FeignConfig.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/api/MemberController.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/MemberSubscriptionResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/PackageProductResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/service/MemberService.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/entity/Subscription.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/repository/SubscriptionRepository.java
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/ProductExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/api/PackageProductController.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/entity/PackageProductImage.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/repository/PackageProductImageRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/repository/PackageProductRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
Labels: ✨feature

#69 feat: FCM 알림 설정
  backend/live/src/main/java/org/samtuap/inong/common/handler/GlobalExceptionHandler.java
  backend/member/.gitignore
  backend/member/build.gradle
  backend/member/src/main/java/org/samtuap/inong/common/exceptionType/NotificationExceptionType.java
  backend/member/src/main/java/org/samtuap/inong/common/handler/GlobalExceptionHandler.java
  backend/member/src/main/java/org/samtuap/inong/config/FcmConfig.java
  backend/member/src/main/java/org/samtuap/inong/config/NotificationExceptionType.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/entity/Member.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/api/FcmController.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/dto/FcmTokenSaveRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/entity/Notification.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/repository/NotificationRepository.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/service/FcmService.java
  backend/member/src/main/resources/application-local.yml
  backend/member/src/main/resources/data.sql
  backend/order/src/main/java/org/samtuap/inong/common/handler/GlobalExceptionHandler.java
  backend/product/.gitignore
  backend/product/build.gradle
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/NotificationExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/common/handler/GlobalExceptionHandler.java
  backend/product/src/main/java/org/samtuap/inong/config/FCMConfig.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/entity/Seller.java
  backend/product/src/main/resources/application-local.yml
Labels: ✨feature

#71 feat:상품 조회 구현
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/SellerPackageListGetResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/repository/PackageProductRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/SellerController.java
Labels: ✨feature

#73 feature: 판매자 상품 삭제 API
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/SellerController.java
Labels: ✨feature

#75 feat: 알림 보내기 API 구현, 농장 공지 글이 등록 됐을 때 카프카로 알림 보내기
  backend/member/src/main/java/org/samtuap/inong/common/exceptionType/NotificationExceptionType.java
  backend/member/src/main/java/org/samtuap/inong/config/KafkaConsumerConfig.java
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/api/.gitkeep
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/api/FavoritesController.java
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/dto/.gitkeep
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/dto/FollowersGetResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/entity/Favorites.java
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/repository/FavoritesRepository.java
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/service/.gitkeep
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/service/FavoritesService.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/api/FcmController.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/dto/KafkaNotificationRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/dto/NotificationIssueRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/service/FcmService.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/api/.gitkeep
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/api/SubscriptionController.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/service/.gitkeep
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/service/SubscriptionService.java
  backend/product/src/main/java/org/samtuap/inong/common/client/MemberFeign.java
  backend/product/src/main/java/org/samtuap/inong/config/KafkaProducerConfig.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/dto/FollowersGetResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/dto/KafkaNotificationRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/service/FarmNoticeService.java
Labels: ✨feature

#77 feat:판매자 상품 수정 기능 구현
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductUpdateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/entity/PackageProduct.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/repository/PackageProductImageRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductImageService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/S3Service.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/SellerController.java
Labels: ✨feature

#82 feature: 유저가 즐겨찾기 한 농장의 진행 중인 라이브 목록 조회
  backend/live/src/main/java/org/samtuap/inong/domain/live/api/.gitkeep
  backend/live/src/main/java/org/samtuap/inong/domain/live/api/LiveController.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/dto/.gitkeep
  backend/live/src/main/java/org/samtuap/inong/domain/live/dto/FavoritesLiveListResponse.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/entity/Live.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/repository/LiveRepository.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/service/.gitkeep
  backend/live/src/main/java/org/samtuap/inong/domain/live/service/LiveService.java
  backend/live/src/main/resources/application-local.yml
  backend/member/src/main/java/org/samtuap/inong/common/client/ProductFeign.java
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/api/FavoritesController.java
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/dto/FavoritesLiveListResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/repository/FavoritesRepository.java
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/service/FavoritesService.java
  backend/product/src/main/java/org/samtuap/inong/common/client/LiveFeign.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/api/FarmController.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/FavoritesLiveListResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/repository/FarmRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
Labels: ✨feature

#83 feat:진행중인 라이브 목록 조회
  backend/live/src/main/java/org/samtuap/inong/common/client/FarmFeign.java
  backend/live/src/main/java/org/samtuap/inong/config/FeignConfig.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/api/LiveController.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/dto/ActiveLiveListGetResponse.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/dto/FarmResponse.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/entity/Live.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/repository/LiveRepository.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/service/LiveService.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/api/FarmController.java
Labels: ✨feature

#90 feat: 일반 회원이 즐겨찾기한 농장 목록 조회
  backend/member/src/main/java/org/samtuap/inong/common/client/ProductFeign.java
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/repository/FavoritesRepository.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/api/MemberController.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/FarmFavoriteResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/MemberFavoriteFarmResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/service/MemberService.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/api/FarmController.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/FarmFavoriteResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/repository/FarmRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
Labels: ✨feature

#91 feat:유저 라이브 쿠폰 발급 기능
  backend/order/src/main/java/org/samtuap/inong/common/exceptionType/CouponExceptionType.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/api/CouponController.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/dto/MemberCouponRelationRequest.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/dto/MemberCouponRelationResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/entity/MemberCouponRelation.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/repository/MemberCouponRelationRepository.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/service/CouponService.java
Labels: ✨feature

#93 feat: 리뷰 생성
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/ReviewExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/domain/review/api/.gitkeep
  backend/product/src/main/java/org/samtuap/inong/domain/review/api/ReviewController.java
  backend/product/src/main/java/org/samtuap/inong/domain/review/dto/.gitkeep
  backend/product/src/main/java/org/samtuap/inong/domain/review/dto/ReviewCreateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/review/dto/ReviewImageResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/review/dto/ReviewResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/review/entity/Review.java
  backend/product/src/main/java/org/samtuap/inong/domain/review/entity/ReviewImage.java
  backend/product/src/main/java/org/samtuap/inong/domain/review/repository/ReviewImageRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/review/repository/ReviewRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/review/service/.gitkeep
  backend/product/src/main/java/org/samtuap/inong/domain/review/service/ReviewService.java
Labels: ✨feature

#96 feat: 빌링키 등록 API, 최초 결제 API 구현
  backend/live/src/main/java/org/samtuap/inong/common/handler/GlobalExceptionHandler.java
  backend/member/src/main/java/org/samtuap/inong/common/exceptionType/NotificationExceptionType.java
  backend/member/src/main/java/org/samtuap/inong/common/handler/GlobalExceptionHandler.java
  backend/member/src/main/java/org/samtuap/inong/config/FcmConfig.java
  backend/member/src/main/java/org/samtuap/inong/config/NotificationExceptionType.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/api/MemberController.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/MemberAllInfoResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/PackageProductResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/entity/Member.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/service/MemberService.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/api/SubscriptionController.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/dto/.gitkeep
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/dto/BillingKeyRegisterRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/service/SubscriptionService.java
  backend/order/.gitignore
  backend/order/src/main/java/org/samtuap/inong/common/client/MemberFeign.java
  backend/order/src/main/java/org/samtuap/inong/common/client/ProductFeign.java
  backend/order/src/main/java/org/samtuap/inong/common/exceptionType/CouponExceptionType.java
  backend/order/src/main/java/org/samtuap/inong/common/exceptionType/OrderExceptionType.java
  backend/order/src/main/java/org/samtuap/inong/common/handler/GlobalExceptionHandler.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/entity/MemberCouponRelation.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/repository/CouponRepository.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/repository/MemberCouponRelationRepository.java
  backend/order/src/main/java/org/samtuap/inong/domain/delivery/dto/PackageProductResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/delivery/entity/Delivery.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/api/OrderController.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/MemberAllInfoResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/PackageProductOrderResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/PaymentRequest.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/PaymentResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/entity/Ordering.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
  backend/order/src/main/resources/application-local.yml
  backend/product/.gitignore
  backend/product/src/main/java/org/samtuap/inong/common/handler/GlobalExceptionHandler.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductResponse.java
  backend/product/src/main/resources/application-local.yml
Labels: ✨feature

#95 feature: elastic search를 활용한 검색 기능 구현
  backend/product/build.gradle
  backend/product/src/main/java/org/samtuap/inong/search/config/ElasticsearchConfig.java
  backend/product/src/main/java/org/samtuap/inong/search/controller/SearchController.java
  backend/product/src/main/java/org/samtuap/inong/search/document/FarmDocument.java
  backend/product/src/main/java/org/samtuap/inong/search/repository/FarmSearchRepository.java
  backend/product/src/main/java/org/samtuap/inong/search/service/SearchService.java
  backend/product/src/main/resources/application-local.yml
Labels: ✨feature

#100 feat: 일반 회원이 구독한 패키지 목록 조회
  backend/member/src/main/java/org/samtuap/inong/common/client/ProductFeign.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/api/MemberController.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/MemberSubscriptionListResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/PackageProductSubsResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/service/MemberService.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/repository/SubscriptionRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/repository/FarmRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/api/PackageProductController.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductSubsResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/repository/PackageProductImageRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
Labels: ✨feature

#107 chore: seller 토큰 로직 수정
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/SellerController.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/dto/SellerSignUpResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/SellerService.java
Labels: 🧹chore

#102 feat: 리뷰 수정, 삭제
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/ReviewExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/domain/review/api/ReviewController.java
  backend/product/src/main/java/org/samtuap/inong/domain/review/dto/ReviewUpdateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/review/repository/ReviewImageRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/review/repository/ReviewRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/review/service/ReviewService.java
Labels: ✨feature

#113 feat: 판매자 자신의 농장 정보 수정
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/ProductExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/entity/Farm.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/entity/FarmCategory.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/entity/FarmCategoryRelation.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/repository/FarmCategoryRelationRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/repository/FarmRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/SellerController.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/dto/SellerFarmInfoUpdateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/dto/SellerInfoResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/SellerService.java
Labels: ✨feature

#114 chore: 사장님 페이지 > 주문 및 배송관리 코드 수정
  backend/order/src/main/java/org/samtuap/inong/common/client/ProductFeign.java
  backend/order/src/main/java/org/samtuap/inong/domain/delivery/api/DeliveryController.java
  backend/order/src/main/java/org/samtuap/inong/domain/delivery/dto/FarmDetailGetResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/delivery/repository/DeliveryRepository.java
  backend/order/src/main/java/org/samtuap/inong/domain/delivery/service/DeliveryService.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/repository/OrderRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/api/FarmController.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
Labels: 🧹chore

#118 feat: 한달 정기 결제 구현
  backend/member/build.gradle
  backend/member/src/main/java/org/samtuap/inong/common/client/ProductFeign.java
  backend/member/src/main/java/org/samtuap/inong/domain/common/BaseEntity.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/api/SubscriptionController.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/dto/PackageProductListGetRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/dto/PackageProductListGetResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/dto/SubscriptionListGetResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/entity/Subscription.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/repository/SubscriptionRepository.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/service/SubscriptionService.java
  backend/order/build.gradle
  backend/order/src/main/java/org/samtuap/inong/OrderApplication.java
  backend/order/src/main/java/org/samtuap/inong/common/client/MemberFeign.java
  backend/order/src/main/java/org/samtuap/inong/common/exceptionType/OrderExceptionType.java
  backend/order/src/main/java/org/samtuap/inong/common/scheduler/PaymentScheduler.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/api/OrderController.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/SubscriptionListGetResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/entity/Ordering.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
  backend/order/src/main/java/org/samtuap/inong/domain/receipt/entity/Receipt.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/api/PackageProductController.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductListGetRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
Labels: ✨feature

#122 feat: 판매자 이메일 인증 기능
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
  backend/product/build.gradle
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/ProductExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/SellerExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/config/RedisConfig.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/EmailVerificationController.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/SellerController.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/dto/EmailRequestDto.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/EmailVerificationService.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/MailService.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/RedisTool.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/SellerService.java
Labels: 🧹chore, ✨feature

#120 feat: 정기 구독 신청, 취소 API 구현
  backend/member/src/main/java/org/samtuap/inong/common/exceptionType/SubscriptionExceptionType.java
  backend/member/src/main/java/org/samtuap/inong/domain/common/BaseEntity.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/api/SubscriptionController.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/dto/KafkaSubscribeProductRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/entity/Subscription.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/service/SubscriptionService.java
  backend/order/src/main/java/org/samtuap/inong/config/KafkaProducerConfig.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/api/OrderController.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/KafkaSubscribeProductRequest.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/service/FarmNoticeService.java
Labels: ✨feature

#124 feat: 판매자 회원 비밀번호 변경
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/SellerController.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/dto/SellerPasswordUpdateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/entity/Seller.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/SellerService.java
Labels: ✨feature

#130 feat: 판매자 농장 생성
  backend/product/src/main/java/org/samtuap/inong/domain/farm/api/FarmController.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/FarmCreateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/FarmCreateResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/entity/Farm.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductCreateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductCreateResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductUpdateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/entity/PackageProduct.java
Labels: 🧹chore, ✨feature

#135 chore: 패키지 상세 정보에 상품 설명 추가
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductResponse.java
Labels: 🧹chore

#137 enhance: 주문, 영수증 롤백
  backend/member/src/main/java/org/samtuap/inong/common/exceptionType/SubscriptionExceptionType.java
  backend/member/src/main/java/org/samtuap/inong/config/KafkaProducerConfig.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/api/MemberController.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/service/MemberService.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/api/SubscriptionController.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/dto/KafkaOrderRollbackRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/service/SubscriptionService.java
  backend/order/src/main/java/org/samtuap/inong/common/exceptionType/OrderExceptionType.java
  backend/order/src/main/java/org/samtuap/inong/config/KafkaConsumerConfig.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/KafkaOrderRollbackRequest.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/entity/CancelReason.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/entity/Ordering.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/repository/OrderRepository.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
  backend/order/src/main/java/org/samtuap/inong/domain/receipt/entity/PaymentMethod.java
  backend/order/src/main/java/org/samtuap/inong/domain/receipt/entity/PaymentStatus.java
  backend/order/src/main/java/org/samtuap/inong/domain/receipt/entity/Receipt.java
  backend/order/src/main/java/org/samtuap/inong/domain/receipt/repository/ReceiptRepository.java
Labels: 🍀enhancement

#136 feat: 구매자 본인의 배송 현황 리스트 조회
  backend/member/src/main/java/org/samtuap/inong/domain/member/api/MemberController.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/PackageProductResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/service/MemberService.java
  backend/order/src/main/java/org/samtuap/inong/common/client/ProductFeign.java
  backend/order/src/main/java/org/samtuap/inong/domain/delivery/repository/DeliveryRepository.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/api/OrderController.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/OrderListResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/repository/OrderRepository.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductResponse.java
Labels: ✨feature

#142 feat: 구매자의 결제 내역 리스트 조회
  backend/member/src/main/java/org/samtuap/inong/domain/member/service/MemberService.java
  backend/order/src/main/java/org/samtuap/inong/domain/delivery/dto/PackageProductResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/api/OrderController.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/OrderDeliveryListResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/OrderListResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/OrderPaymentListResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/repository/OrderRepository.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
  backend/order/src/main/java/org/samtuap/inong/domain/receipt/entity/Receipt.java
Labels: ✨feature

#147 enhance: 정기구독 실패 시 주문과 영수증 취소 처리
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/dto/KafkaOrderRollbackRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/dto/KafkaSubscribeProductRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/service/SubscriptionService.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/KafkaOrderRollbackRequest.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/KafkaSubscribeProductRequest.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/entity/Ordering.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
  backend/order/src/main/java/org/samtuap/inong/domain/receipt/entity/Receipt.java
Labels: 🍀enhancement

#151 feature: open search (elasticsearch)를 활용한 검색 구현
  backend/product/build.gradle
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/SellerService.java
  backend/product/src/main/java/org/samtuap/inong/search/config/ElasticsearchConfig.java
  backend/product/src/main/java/org/samtuap/inong/search/config/OpenSearchConfig.java
  backend/product/src/main/java/org/samtuap/inong/search/controller/FarmSearchController.java
  backend/product/src/main/java/org/samtuap/inong/search/controller/IntegratedSearchController.java
  backend/product/src/main/java/org/samtuap/inong/search/controller/PackageProductSearchController.java
  backend/product/src/main/java/org/samtuap/inong/search/controller/SearchController.java
  backend/product/src/main/java/org/samtuap/inong/search/document/FarmDocument.java
  backend/product/src/main/java/org/samtuap/inong/search/document/PackageProductDocument.java
  backend/product/src/main/java/org/samtuap/inong/search/repository/FarmSearchRepository.java
  backend/product/src/main/java/org/samtuap/inong/search/repository/PackageProductSearchRepository.java
  backend/product/src/main/java/org/samtuap/inong/search/service/FarmSearchService.java
  backend/product/src/main/java/org/samtuap/inong/search/service/PackageProductSearchService.java
  backend/product/src/main/java/org/samtuap/inong/search/service/SearchService.java
  backend/product/src/main/resources/application-local.yml
Labels: ✨feature

#157 fix: localhost:8081 cors 허용
  backend/apigateway/build.gradle
  backend/apigateway/src/main/java/org/samtuap/inong/ApiGatewayApplication.java
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
  backend/apigateway/src/main/resources/application-local.yml
  backend/live/src/main/java/org/samtuap/inong/config/WebConfig.java
  backend/member/src/main/java/org/samtuap/inong/config/WebConfig.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/api/MemberController.java
  backend/member/src/main/resources/application-local.yml
  backend/order/src/main/java/org/samtuap/inong/config/WebConfig.java
  backend/product/src/main/java/org/samtuap/inong/config/WebConfig.java
Labels: 🚧 fix

#154 feat: 구매자 결제 영수증 조회
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/OrderPaymentListResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/receipt/api/.gitkeep
  backend/order/src/main/java/org/samtuap/inong/domain/receipt/api/ReceiptController.java
  backend/order/src/main/java/org/samtuap/inong/domain/receipt/dto/.gitkeep
  backend/order/src/main/java/org/samtuap/inong/domain/receipt/dto/ReceiptInfoResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/receipt/service/.gitkeep
  backend/order/src/main/java/org/samtuap/inong/domain/receipt/service/ReceiptService.java
Labels: ✨feature

#161 chore: presignedUrl 발급 과정 수정
  backend/product/build.gradle
  backend/product/src/main/java/org/samtuap/inong/S3/FileService.java
  backend/product/src/main/java/org/samtuap/inong/S3/api/ImageUploadController.java
  backend/product/src/main/java/org/samtuap/inong/S3/dto/PresignedRequest.java
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/FarmExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/config/AwsConfig.java
  backend/product/src/main/java/org/samtuap/inong/config/S3Config.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/api/S3Controller.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductImageService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/S3Service.java
Labels: 🧹chore

#159 feature: 동상이농에 라이브 프론트 코드 붙여보기
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
  backend/apigateway/src/main/resources/application-local.yml
  backend/live/build.gradle
  backend/live/src/main/java/org/samtuap/inong/domain/live/api/LiveController.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/api/OpenViduController.java
  backend/live/src/main/resources/application-local.yml
  backend/member/src/main/resources/application-local.yml
Labels: ✨feature

#166 feat: 판매자 페이지 - 매출 내역
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/api/MemberController.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/repository/MemberRepository.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/service/MemberService.java
  backend/order/src/main/java/org/samtuap/inong/common/client/MemberFeign.java
  backend/order/src/main/java/org/samtuap/inong/common/client/ProductFeign.java
  backend/order/src/main/java/org/samtuap/inong/common/exceptionType/OrderExceptionType.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/api/OrderBackOfficeController.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/SalesDataGetResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/SalesElementGetResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/SalesTableGetRequest.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/entity/Ordering.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/repository/OrderRepository.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderBackOfficeService.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
  backend/order/src/main/java/org/samtuap/inong/domain/receipt/repository/ReceiptRepository.java
  backend/product/src/main/java/org/samtuap/inong/common/client/MemberFeign.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/api/FarmNoticeController.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/api/PackageProductController.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/repository/PackageProductRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/SellerController.java
Labels: ✨feature

#167 chore: PathVariable farmId 제거
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/api/FarmNoticeController.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/service/FarmNoticeService.java
Labels: 🧹chore

#168 chore: 컨트롤러 반환 타입 수정 및 페이징 처리 추가
  backend/product/src/main/java/org/samtuap/inong/config/S3Config.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/api/FarmNoticeController.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/dto/CommentListResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/repository/FarmNoticeRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/repository/NoticeCommentRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/service/FarmNoticeService.java
Labels: 🧹chore

#174 chore: 공지사항 목록에 해당 글에 대한 댓글 수 반환
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/dto/NoticeListResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/service/FarmNoticeService.java
Labels: 🧹chore

#170 chore:허용URL 수정
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/api/FarmController.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/api/FarmNoticeController.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/api/PackageProductController.java
  backend/product/src/main/java/org/samtuap/inong/domain/review/api/ReviewController.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/SellerController.java
Labels: 🧹chore

#175 feat: 실시간 채팅 기능 구현
  backend/apigateway/src/main/resources/application-local.yml
  backend/live/build.gradle
  backend/live/src/main/java/org/samtuap/inong/LiveApplication.java
  backend/live/src/main/java/org/samtuap/inong/common/client/MemberFeign.java
  backend/live/src/main/java/org/samtuap/inong/common/exceptionType/ChatExceptionType.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/api/.gitkeep
  backend/live/src/main/java/org/samtuap/inong/domain/chat/api/ChatController.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/dto/.gitkeep
  backend/live/src/main/java/org/samtuap/inong/domain/chat/dto/ChatMessageRequest.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/dto/ChatMessageResponse.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/dto/MemberDetailResponse.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/dto/MessageType.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/entity/Chat.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/kafka/KafkaConstants.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/kafka/KafkaConsumerConfig.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/kafka/KafkaMessageListener.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/kafka/KafkaProducerConfig.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/service/.gitkeep
  backend/live/src/main/java/org/samtuap/inong/domain/chat/service/ChatService.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/websocket/JwtProvider.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/websocket/SecretKeyFactory.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/websocket/SocketController.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/websocket/StompHandler.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/websocket/WebSocketConfiguration.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/api/OpenViduController.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/dto/ActiveLiveListGetResponse.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/service/LiveService.java
  backend/live/src/main/resources/application-local.yml
Labels: ✨feature

#179 chore: notice detail & 댓글 페이징 처리
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/dto/NoticeDetailResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/repository/NoticeCommentRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/service/FarmNoticeService.java
Labels: 🧹chore
