Repository samtuap/dongsanginong-server, pull requests merged in 2024-10, with the labels that each got.

#188 chore: 자잘자잘 수정
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/dto/CommentListResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/service/FarmNoticeService.java
Labels: 🧹chore

#186 chore: 판매자 탈퇴 로직 수정
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/SellerExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/SellerController.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/dto/SellerSignInResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/SellerService.java
Labels: 🧹chore, 🚧 fix

#189 fix: 클라이언트 요청 시 memberId 헤더로 처리
  backend/member/src/main/java/org/samtuap/inong/domain/member/api/MemberController.java
Labels: 🚧 fix

#192 feat: 전체 카테고리 리스트 불러오기
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/FarmExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/api/FarmController.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/repository/FarmRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/dto/FarmCategoryResponse.java
Labels: ✨feature, 🚧 fix

#193 chore: filter에 라이브 목록 추가
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
Labels: 🧹chore

#200 chore: 농장 수정 로직 seller > farm 으로 이동
  backend/product/src/main/java/org/samtuap/inong/domain/farm/api/FarmController.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/SellerController.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/SellerService.java
Labels: 🧹chore

#199 chore:쿠폰 관련 로직 수정
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/api/CouponController.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/dto/MemberCouponListResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/service/CouponService.java
Labels: 🧹chore

#197 chore: 패키지 관련 로직 수정
  backend/product/src/main/java/org/samtuap/inong/domain/product/api/PackageProductController.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductCreateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductCreateResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/SellerPackageListGetResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/entity/PackageProduct.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/SellerController.java
Labels: 🧹chore

#204 fix: 주문 결제 목록 List > Pageable 변경
  backend/order/src/main/java/org/samtuap/inong/domain/order/api/OrderController.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/repository/OrderRepository.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
Labels: 🚧 fix

#205 feat: 판매 중인 패키지 설명과 패키지 목록 조회
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/api/PackageProductController.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductForSaleListResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/repository/PackageProductRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
Labels: ✨feature

#206 feat: 라이브 스트리밍 구현
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
  backend/live/src/main/java/org/samtuap/inong/common/client/FarmFeign.java
  backend/live/src/main/java/org/samtuap/inong/common/exceptionType/LiveExceptionType.java
  backend/live/src/main/java/org/samtuap/inong/config/OpenViduConfig.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/api/OpenViduController.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/dto/ActiveLiveListGetResponse.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/dto/FarmDetailGetResponse.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/dto/LiveSessionRequest.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/dto/LiveSessionResponse.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/entity/Live.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/repository/LiveRepository.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/service/LiveService.java
Labels: ✨feature

#212 chore: live 목록 페이징 처리 & chore: 공지 목록 정렬 수정
  backend/live/src/main/java/org/samtuap/inong/domain/live/api/LiveController.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/repository/LiveRepository.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/service/LiveService.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/api/FarmNoticeController.java
Labels: 🧹chore

#217 fix: 메인페이지를 위한 dto, 쿼리 수정
  backend/order/src/main/java/org/samtuap/inong/domain/order/repository/OrderRepository.java
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/ProductExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/TopPackageGetResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/repository/PackageProductImageRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/repository/PackageProductRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
Labels: 🚧 fix

#218 feat&chore: elastic search와 rdbms 성능 테스트 코드 구현
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
  backend/product/build.gradle
  backend/product/src/main/java/org/samtuap/inong/domain/farm/repository/FarmRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/SellerService.java
  backend/product/src/main/java/org/samtuap/inong/search/controller/FarmSearchController.java
  backend/product/src/main/java/org/samtuap/inong/search/controller/SearchTestController.java
  backend/product/src/main/java/org/samtuap/inong/search/dto/BaseResponse.java
  backend/product/src/main/java/org/samtuap/inong/search/service/FakeDataService.java
  backend/product/src/main/java/org/samtuap/inong/search/service/FarmSearchService.java
  backend/product/src/main/java/org/samtuap/inong/search/service/SearchTestService.java
Labels: 🧹chore, ✨feature

#219 feat: 채팅 구현 및 추가적인 api 구현
  backend/live/src/main/java/org/samtuap/inong/common/client/FarmFeign.java
  backend/live/src/main/java/org/samtuap/inong/common/exceptionType/ChatExceptionType.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/api/ChatController.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/dto/ChatMessageRequest.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/dto/MessageType.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/dto/SellerInfoResponse.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/service/ChatService.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/websocket/SocketController.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/websocket/StompHandler.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/dto/ActiveLiveListGetResponse.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/dto/FavoritesLiveListResponse.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/entity/Live.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/service/LiveService.java
Labels: ✨feature

#221 chore: 상품에 원산지 추가
  backend/live/src/main/java/org/samtuap/inong/domain/chat/api/ChatController.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductCreateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductCreateResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductUpdateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/entity/PackageProduct.java
Labels: 🧹chore

#225 chore: liveId를 sessionId로 변경 및 즐겨찾기 농장 시청인원 표시
  backend/live/src/main/java/org/samtuap/inong/domain/chat/api/ChatController.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/dto/ChatMessageRequest.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/kafka/KafkaMessageListener.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/service/ChatService.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/websocket/SocketController.java
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/dto/FavoritesLiveListResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/FavoritesLiveListResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
Labels: 🧹chore, ✨feature

#226 feat: 농장 정보 수정 및 조회
  backend/product/src/main/java/org/samtuap/inong/domain/farm/api/FarmController.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/FarmInfoResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/dto/SellerFarmInfoUpdateRequest.java
Labels: ✨feature

#227 chore: top10 패키지 응답 값에 price 추가
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/TopPackageGetResponse.java
Labels: 🚧 fix

#231 chore: application-local.yml 수정
  backend/live/src/main/resources/application-local.yml
  backend/member/src/main/resources/application-local.yml
  backend/order/src/main/resources/application-local.yml
  backend/product/src/main/resources/application-local.yml
Labels: 🧹chore

#239 chore: 라이브 목록 response에 sessionId 추가
  backend/live/src/main/java/org/samtuap/inong/domain/live/dto/ActiveLiveListGetResponse.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/dto/FavoritesLiveListResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/dto/FavoritesLiveListResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/FavoritesLiveListResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
Labels: 🧹chore

#240 chore: websocket 연결 해제 및 강퇴 기능 구현
  backend/live/src/main/java/org/samtuap/inong/common/exceptionType/ChatExceptionType.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/api/ChatController.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/dto/KickMessage.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/service/ChatService.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/websocket/SocketController.java
Labels: 🧹chore, ✨feature

#241 fix: 배송 목록 List > Pageable 변경
  backend/order/src/main/java/org/samtuap/inong/domain/order/api/OrderController.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/OrderDeliveryListResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
Labels: 🚧 fix

#243 feat: 좋아요 누르기 기능 추가, JwtGlobalFilter 수정
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
  backend/member/src/main/java/org/samtuap/inong/common/client/ProductFeign.java
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/api/FavoritesController.java
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/dto/FavoriteGetResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/entity/Favorites.java
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/repository/FavoritesRepository.java
  backend/member/src/main/java/org/samtuap/inong/domain/favorites/service/FavoritesService.java
  backend/product/src/main/java/org/samtuap/inong/common/client/MemberFeign.java
  backend/product/src/main/java/org/samtuap/inong/common/response/FavoriteGetResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/api/FarmController.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/FarmListGetResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/entity/Farm.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
Labels: 🧹chore, ✨feature

#250 chore: 라이브 & 채팅 반환 dto에 profile farmName, profileImage 추가
  backend/live/src/main/java/org/samtuap/inong/domain/live/dto/FarmResponse.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/dto/LiveSessionResponse.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/service/LiveService.java
Labels: 🧹chore

#255 feat: 라이브 관련 dto에 category 추가 & chore: 변수값 빠진 부분 추가
  backend/live/src/main/java/org/samtuap/inong/domain/chat/api/ChatController.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/dto/ActiveLiveListGetResponse.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/dto/LiveSessionRequest.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/entity/Live.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/service/LiveService.java
Labels: 🧹chore, ✨feature

#254 fix: 주문을 위한 API 수정, 쿠폰 관련 API의 uri 수정, 주문시 적용 가능한 쿠폰 조회 기능 추가
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/api/MemberController.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/PaymentMethodGetResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/entity/Member.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/entity/PaymentMethodType.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/api/SubscriptionController.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/dto/BillingKeyRegisterRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/service/SubscriptionService.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/api/CouponController.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/dto/AvailableCouponGetResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/dto/AvailableCouponListGetResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/repository/MemberCouponRelationRepository.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/service/CouponService.java
Labels: ✨feature, 🚧 fix

#257 feat & chore: 공지사항 > 댓글에 seller도 작성 및 조회 할 수 있도록 추가 + 수정/삭제
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/api/FarmNoticeController.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/dto/CommentCreateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/dto/CommentListResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/dto/NoticeDetailResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/entity/NoticeComment.java
  backend/product/src/main/java/org/samtuap/inong/domain/farmNotice/service/FarmNoticeService.java
Labels: 🧹chore, ✨feature

#258 fix: 회원 배송 조회 다대일 수정
  backend/order/src/main/java/org/samtuap/inong/domain/delivery/repository/DeliveryRepository.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/OrderDeliveryListResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
Labels: 🚧 fix

#262 fix: 마이페이지 결제 내역 및 배송 내역 정렬
  backend/order/src/main/java/org/samtuap/inong/domain/delivery/api/DeliveryController.java
  backend/order/src/main/java/org/samtuap/inong/domain/delivery/dto/DeliveryListResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/delivery/service/DeliveryService.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/api/OrderController.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/OrderDeliveryListResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/repository/OrderRepository.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
Labels: 🚧 fix

#269 fix: farmList 응답값에 farmIntro 추가
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/dto/KafkaOrderRollbackRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/dto/KafkaSubscribeProductRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/service/SubscriptionService.java
  backend/order/src/main/java/org/samtuap/inong/common/exceptionType/CouponExceptionType.java
  backend/order/src/main/java/org/samtuap/inong/common/exceptionType/ReceiptExceptionType.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/KafkaOrderRollbackRequest.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/KafkaSubscribeProductRequest.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderTestService.java
  backend/order/src/main/java/org/samtuap/inong/domain/receipt/repository/ReceiptRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/FarmListGetResponse.java
Labels: 🚧 fix

#272 chore: 판매자 회원가입 로직 수정
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/SellerExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/api/SellerController.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/MailService.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/RedisTool.java
  backend/product/src/main/java/org/samtuap/inong/domain/seller/service/SellerService.java
Labels: 🧹chore

#266 fix: 주문시 Farm 엔티티의 주문수(orderCount)가 증가되도록 코드 추가
  backend/order/src/main/java/org/samtuap/inong/domain/order/api/OrderController.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/KafkaOrderCountUpdateRequest.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/FarmExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/config/KafkaConsumerConfig.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/KafkaOrderCountUpdateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/entity/Farm.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
Labels: 🚧 fix

#274 chore: 라이브 강퇴 기능 수정
  backend/live/src/main/java/org/samtuap/inong/domain/chat/dto/KickMessage.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/service/ChatService.java
Labels: 🧹chore

#275 fix: 판매자 판매건수, 매출 내역 페이지 관련 API 수정
  backend/order/src/main/java/org/samtuap/inong/common/client/ProductFeign.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/api/OrderBackOfficeController.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/PackageOrderCount.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/PackageStatisticResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/SalesDataByYearAndMonth.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/SalesDataGetResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/SalesDataWithPackagesGetResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/repository/OrderRepository.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderBackOfficeService.java
  backend/order/src/main/java/org/samtuap/inong/domain/receipt/repository/ReceiptRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/api/PackageProductController.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageStatisticResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/entity/PackageProduct.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/repository/PackageProductRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
Labels: 🚧 fix

#263 feat: 농장 상세 페이지 캐싱 구현
  backend/product/build.gradle
  backend/product/src/main/java/org/samtuap/inong/ProductApplication.java
  backend/product/src/main/java/org/samtuap/inong/config/RedisCacheConfig.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/FarmDetailGetResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
Labels: ✨feature

#277 feat: 패키지 위시리스트 기능 구현 (담기/취소/조회)
  backend/member/src/main/java/org/samtuap/inong/common/client/ProductFeign.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/PackageProductResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/wishlist/api/WishListController.java
  backend/member/src/main/java/org/samtuap/inong/domain/wishlist/entity/WishList.java
  backend/member/src/main/java/org/samtuap/inong/domain/wishlist/repository/WishListRepository.java
  backend/member/src/main/java/org/samtuap/inong/domain/wishlist/service/WishListService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/api/PackageProductController.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/entity/PackageProduct.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
Labels: ✨feature

#281 chore: farmFavoritesResponse에 farmId 값 추가
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/FarmFavoriteResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/MemberFavoriteFarmResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/service/MemberService.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/FarmFavoriteResponse.java
Labels: 🧹chore

#283 chore: 라이브 화면에서 시청인원 표시
  backend/live/src/main/java/org/samtuap/inong/domain/live/api/LiveController.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/service/LiveService.java
Labels: 🧹chore

#285 fix: 정기 구독시, 이미 구독 중인지 확인하는 코드 추가
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/api/SubscriptionController.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/dto/SubscribeProductRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/dto/SubscriptionGetResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/repository/SubscriptionRepository.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/service/SubscriptionService.java
  backend/order/build.gradle
  backend/order/src/main/java/org/samtuap/inong/common/client/MemberFeign.java
  backend/order/src/main/java/org/samtuap/inong/common/exceptionType/OrderExceptionType.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/api/OrderController.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/PaymentRequest.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/SubscribeProductRequest.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/SubscriptionInfoGetResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
Labels: 🚧 fix

#290 fix: 배송 주기 에러 수정
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
Labels: 🚧 fix

#291 feat: 메인 페이지 > 라이브 목록 시청순 best5 출력
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/api/LiveController.java
Labels: ✨feature

#287 패키지 상세 페이지 캐싱 구현
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
  backend/product/src/main/java/org/samtuap/inong/domain/review/service/ReviewService.java
Labels: ✨feature

#299 chore: 구독 취소 기능 코드 수정
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/MemberSubsCancelRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/MemberSubscriptionListResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/dto/PackageProductResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/subscription/service/SubscriptionService.java
Labels: 🧹chore

#300 feat: 알림 조회, 알림 읽음처리 API 구현
  backend/member/src/main/java/org/samtuap/inong/domain/notification/api/NotificationController.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/dto/NotificationGetResponse.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/dto/NotificationIssueRequest.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/entity/Notification.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/repository/NotificationRepository.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/service/FcmService.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/service/NotificationService.java
Labels: ✨feature, 🚧 fix

#302 fix: PackageProduct Entity - OrderCount 추가
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/KafkaOrderCountUpdateRequest.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/KafkaOrderCountUpdateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductCreateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/entity/PackageProduct.java
Labels: ✨feature, 🚧 fix

#298 feat: 쿠폰 발급 동시성 이슈 해결
  backend/live/src/main/java/org/samtuap/inong/domain/chat/api/ChatController.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/dto/CouponMessage.java
  backend/order/build.gradle
  backend/order/src/main/java/org/samtuap/inong/common/exceptionType/CouponExceptionType.java
  backend/order/src/main/java/org/samtuap/inong/config/KafkaConsumerConfig.java
  backend/order/src/main/java/org/samtuap/inong/config/KafkaProducerConfig.java
  backend/order/src/main/java/org/samtuap/inong/config/RedisConfig.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/api/CouponController.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/consumer/CouponConsumer.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/dto/CouponRequestMessage.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/entity/Coupon.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/producer/CouponProducer.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/repository/CouponRedisRepository.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/repository/MemberCouponRelationRepository.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/service/CouponService.java
  backend/order/src/main/resources/application-local.yml
  backend/order/src/test/java/org/samtuap/inong/coupon/CouponConsumerTest.java
  backend/order/src/test/java/org/samtuap/inong/coupon/CouponProducerTest.java
  backend/order/src/test/java/org/samtuap/inong/coupon/CouponServiceTest.java
Labels: ✨feature

#304 fix: fcmToken 삭제 API 추가
  backend/member/src/main/java/org/samtuap/inong/domain/member/api/MemberController.java
  backend/member/src/main/java/org/samtuap/inong/domain/member/service/MemberService.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/api/FcmController.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/repository/FcmTokenRepository.java
  backend/member/src/main/java/org/samtuap/inong/domain/notification/service/FcmService.java
  backend/product/src/main/java/org/samtuap/inong/domain/notification/api/FcmController.java
  backend/product/src/main/java/org/samtuap/inong/domain/notification/repository/FcmTokenRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/notification/service/FcmService.java
Labels: ✨feature, 🚧 fix

#307 feat: 농장 카테고리 필터링 기능 구현
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/ProductExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/api/FarmController.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/dto/FarmListGetResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/repository/FarmCategoryRelationRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/repository/FarmCategoryRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/repository/FarmRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/farm/service/FarmService.java
Labels: ✨feature

#310 chore&refactor: 할인 기능 관련 코드 모두 수정
  backend/product/src/main/java/org/samtuap/inong/common/exceptionType/ProductExceptionType.java
  backend/product/src/main/java/org/samtuap/inong/domain/discount/api/DiscountController.java
  backend/product/src/main/java/org/samtuap/inong/domain/discount/api/DiscountScheduler.java
  backend/product/src/main/java/org/samtuap/inong/domain/discount/dto/DiscountCreateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/discount/dto/DiscountResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/discount/dto/DiscountUpdateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/discount/dto/DiscountUtil.java
  backend/product/src/main/java/org/samtuap/inong/domain/discount/entity/Discount.java
  backend/product/src/main/java/org/samtuap/inong/domain/discount/service/DiscountService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductForSaleListResponse.java
Labels: 🧹chore, 🔮refactor

#311 chore&refactor: discount 등록 관련 코드 변경
  backend/product/src/main/java/org/samtuap/inong/domain/discount/api/DiscountController.java
  backend/product/src/main/java/org/samtuap/inong/domain/discount/api/DiscountScheduler.java
  backend/product/src/main/java/org/samtuap/inong/domain/discount/dto/DiscountCreateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/discount/dto/DiscountResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/discount/dto/DiscountUpdateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/discount/entity/Discount.java
  backend/product/src/main/java/org/samtuap/inong/domain/discount/repository/DiscountRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/discount/service/DiscountService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductCreateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/entity/PackageProduct.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/repository/PackageProductRepository.java
Labels: 🧹chore, 🔮refactor

#312 chore: 라이브 쿠폰 등록
  backend/live/src/main/java/org/samtuap/inong/common/client/OrderFeign.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/dto/ChatMessageRequest.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/dto/CouponDetailResponse.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/service/ChatService.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/api/LiveController.java
  backend/live/src/main/java/org/samtuap/inong/domain/live/service/LiveService.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/api/CouponController.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/dto/CouponDetailResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/producer/CouponProducer.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/service/CouponService.java
Labels: 🧹chore, ✨feature

#314 feat: 세일 관련 코드 추가
  backend/product/src/main/java/org/samtuap/inong/domain/discount/repository/DiscountRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/AllPackageListResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/TopPackageGetResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
Labels: ✨feature

#317 chore: 농장 패키지 목록 페이징 처리
  backend/product/src/main/java/org/samtuap/inong/domain/product/api/PackageProductController.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/repository/PackageProductRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
Labels: 🧹chore

#320 fix: 할인건이 있는 상품 목록 출력하는 코드 구현
  backend/product/src/main/java/org/samtuap/inong/domain/product/api/PackageProductController.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductDiscountResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/repository/PackageProductRepository.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
Labels: ✨feature, 🚧 fix

#319 feat: 상품 할인 관련 코드 캐싱
  backend/product/src/main/java/org/samtuap/inong/domain/discount/api/DiscountScheduler.java
  backend/product/src/main/java/org/samtuap/inong/domain/discount/service/DiscountService.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
Labels: ✨feature

#323 fix: Ordering에 주문 번호 추가
  backend/member/src/main/java/org/samtuap/inong/domain/notification/api/NotificationController.java
  backend/order/src/main/java/org/samtuap/inong/common/exceptionType/OrderExceptionType.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/OrderPaymentListResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/dto/SalesElementGetResponse.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/entity/Ordering.java
  backend/order/src/main/java/org/samtuap/inong/domain/order/service/OrderService.java
  backend/order/src/main/java/org/samtuap/inong/domain/receipt/dto/ReceiptInfoResponse.java
Labels: 🚧 fix

#322 fix: 무제한 쿠폰 발급 수정
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/producer/CouponProducer.java
  backend/order/src/main/java/org/samtuap/inong/domain/coupon/repository/CouponRedisRepository.java
Labels: 🚧 fix

#326 feat: dto에 세일 구현
  backend/product/src/main/java/org/samtuap/inong/domain/discount/api/DiscountScheduler.java
  backend/product/src/main/java/org/samtuap/inong/domain/discount/dto/DiscountUtil.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductForSaleListResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/service/PackageProductService.java
Labels: ✨feature

#327 feat: 채팅 이모지 기능 구현
  backend/live/src/main/java/org/samtuap/inong/domain/chat/api/ChatController.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/dto/ChatMessageRequest.java
  backend/live/src/main/java/org/samtuap/inong/domain/chat/service/ChatService.java
Labels: ✨feature

#331 chore: 각 모듈마다 healthcheck api 추가
  backend/apigateway/src/main/java/org/samtuap/inong/securities/JwtGlobalFilter.java
  backend/live/k8s/live-depl.yml
  backend/live/k8s/live-service.yml
  backend/live/src/main/java/org/samtuap/inong/domain/live/api/LiveController.java
  backend/member/k8s/member-depl.yml
  backend/member/k8s/member-service.yml
  backend/order/k8s/order-depl.yml
  backend/order/k8s/order-service.yml
  backend/order/src/main/java/org/samtuap/inong/domain/order/api/OrderController.java
  backend/product/k8s/product-depl.yml
  backend/product/k8s/product-service.yml
  backend/product/src/main/java/org/samtuap/inong/domain/product/api/PackageProductController.java
Labels: 🧹chore, ✨feature

#330 chore: k8s 배포를 위한 ingress, certificate 자원 생성 스크립트 작성
  .gitignore
  backend/product/src/main/resources/application-dev.yml
  backend/product/src/main/resources/application-local.yml
  k8s/certificate.yml
  k8s/ingress.yml
Labels: ⚙️setting

#337 feat: 상품 상세 소개 추가
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductCreateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductResponse.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/dto/PackageProductUpdateRequest.java
  backend/product/src/main/java/org/samtuap/inong/domain/product/entity/PackageProduct.java
Labels: ✨feature
